### ISSUE TITLE
[Suggestion] Would it be better to send 400/404 error code instead of 403 when User not found.

### ISSUE THREAD

**Issue by saiteja310** [stackinflow/focial-backend#33]
Need inputs whether it is appropriate to send 
400 Bad Request or 404 Not Found
instead of 403 when the user is not found.

**Comment by fayaz07** [comment]
I guess we can send 400. But if we send 404 it might be as if route not available

**Comment by saiteja310** [comment]
Bad Request is better than Forbidden. 😆 
Up to you guys tbh.  Let me know if you want to change.

**Comment by fayaz07** [comment]
yeah please send a PR
